# version: "3"
# services:
#   randomnote:
#     image: sandipbudhathoki/randomnote:1 # Your pushed image
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=production # Add any env vars your app needs
# version: "3"
# services:
#   randomnote:
#     image: sandipbudhathoki/randomnote:2 # ← Use the correct image version
#     ports:
#       - "8889:3000" # ← Make sure this port is free on your server
#     environment:
#       - NODE_ENV=production
# version: "3"
# services:
#   randomnote:
#     build:
#       context: https://github.com/yourusername/your-repo-name.git
#     ports:
#       - "8889:3000"
version: "3.8"
services:
  randomnote:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:3000"
    restart: always
