version: "3"
services:
  randomnote:
    image: sandipbudhathoki/randomnote:1 # Your pushed image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production # Add any env vars your app needs
