version: "3.8"

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: npm run dev

  # Production service
  nuxt-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: nuxt-app-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    command: npm run start
